const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  base_url: state => state.app.base_url,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  org_name: state => state.user.org_name,
  org_list: state => state.user.org_list,
  org_id: state => state.user.org_id,
  user_id: state => state.user.user_id,
  address_id: state => state.user.address_id,
  user_true_name: state => state.user.user_true_name,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  caseTimeStatus: state => state.settings.caseTimeStatus,
  exhibit_type: state => state.settings.exhibit_type,
  exhibit_time_bg: state => state.settings.exhibit_time_bg,
  case_type: state => state.settings.case_type,
  case_type_origin: state => state.settings.case_type_origin,
  stock_status: state => state.settings.stock_status,
}
export default getters
