@baseUrl = 'http://106.12.68.167/dossier_qd'

# @name getConfirmedByPage
POST {{baseUrl}}/cases/cases/getConfirmedByPage HTTP/1.1
Content-type: application/x-www-form-urlencoded
kf-token: f5acd61bc5af4073a270b2a3c172305b

pageNum=1&pageSize=10&province_id=370000&city_id=370200&area_id=370200
###